import json
import os 
import boto3
from datetime import datetime

s3= boto3.client('s3', endpoint_url=os.environ.get('AWS_ENDPOINT_URL'))
dynamodb = boto3.resource('dynamodb', endpoint_url=os.environ.get('AWS_ENDPOINT_URL'))

S3_BUCKET = os.environ['S3_BUCKET']
DYNAMODB_TABLE = os.environ['DYNAMODB_TABLE']

def lambda_handler(event, context):
    """
    Generates invoice for completed orders and uploads to s3
    """
    try:
        # parse the order from the event
        order_id = event.get('order_id')

        if not order_id:
            return {
                'statusCode': 400,
                'body': json.dumps({'error': 'Missing order_id'})
            }
        print(f'Generating invoice for order: {order_id}')

        # fetch order details from dynamodb
        table = dynamodb.Table(DYNAMODB_TABLE)
        response = table.get_item(Key={'order_id': order_id})

        if 'Item' not in response:
            return {
                'statusCode': 404,
                'body': json.dumps({'error': 'Order not found'})
            }
        order = response['Item']

        # generate invoice content 
        invoice = generate_invoice_content(order)

        # upload invoice to s3
        invoice_key = f'invoices/{order_id}.txt'
        s3.put_object(
            Bucket = S3_BUCKET,
            Key = invoice_key,
            Body = invoice,
            ContentType = 'text/plain'
        )

        print(f'Invoice uploaded to S3: {invoice_key}')

        # update order with invoice reference 
        table.update_item(
            Key = {'order_id': order_id},
            UpdateExpression = 'SET invoice_url = :invoice_url, updated_at = :updated_at',
            ExpressionAttributeValues = {
                ':invoice_url': f's3://{S3_BUCKET}/{invoice_key}',
                ':updated_at': datetime.utcnow().isoformat()
            }
        )

        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'Invoice generated successfully',
                'invoice_url': f"s3://{S3_BUCKET}/{invoice_key}"
            })
        }
    
    except Exception as e:
        print(f'Error getting invoice: {str(e)}')
        return {
            'statusCode': 500,
            'body': json.dumps({'error': 'Internal Server Error'})
        }

def generate_invoice_content(order):
    """
    Generate invoice content as a formatted text
    """
    invoice = f"""
{'='*60}
                         INVOICE
{'='*60}

Invoice Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
Order ID: {order['order_id']}

{'='*60}
CUSTOMER INFORMATION
{'='*60}

Name:  {order['customer_name']}
Email: {order['customer_email']}

{'='*60}
ORDER DETAILS
{'='*60}

Order Date: {order.get('created_at', 'N/A')}
Status:     {order.get('status', 'N/A')}

{'='*60}
ITEMS
{'='*60}

{'Item':<30} {'Qty':>10} {'Price':>10} {'Total':>10}
{'-'*60}
"""
    
    # Add items to invoice
    for item in order['items']:
        name = item.get('name', 'Unknown')
        quantity = item.get('quantity', 1)
        price = item.get('price', 0)
        total = quantity * price
        
        invoice += f"{name:<30} {quantity:>10} ${price:>9.2f} ${total:>9.2f}\n"
    
    # Add totals
    invoice += f"""
{'-'*60}
{'TOTAL:':<42} ${order['total_price']:>16.2f}
{'='*60}

Thank you for your business!

This is an automated invoice generated by Order Processing System.
For any questions, please contact support@example.com

{'='*60}
"""
    
    return invoice
